steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'USER_NAME=${_USER_NAME}'
  - '--build-arg'
  - 'USER_UID=${_USER_UID}'
  - '--target'
  - 'production'
  - '-t'
  - $_IMAGE
  - '.'
  timeout: 300s
# push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', $_IMAGE]
  timeout: 300s
# deploy to Cloud Run with GCS bucket
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - $_SERVICE_NAME
  - '--image'
  - $_IMAGE
  - '--region'
  - $_LOCATION
  - '--execution-environment'
  - 'gen2'
  - '--service-account'
  - 'runtime@${PROJECT_ID}.iam.gserviceaccount.com'
  - '--add-volume'
  - 'name=${_VOLUME_NAME},type=cloud-storage,bucket=${_BUCKET}'
  - '--add-volume-mount'
  - 'volume=${_VOLUME_NAME},mount-path=${_MOUNT_PATH}'
  - '--allow-unauthenticated'
images: [$_IMAGE]
options:
  dynamicSubstitutions: true
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _USER_NAME: 'alanhsieh2000'
  _USER_UID: '1000'
  _LOCATION: 'us-west1'
  _REPOSITORY: 'yfin-mcp-server-images'
  _NAME: 'yfin'
  _IMAGE: '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_NAME}:${SHORT_SHA}'
  _SERVICE_NAME: 'yfin-mcp-service'
  _VOLUME_NAME: 'data'
  _BUCKET: 'yfin-mcp-server-data-v2'
  _MOUNT_PATH: '/app/data'
serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/builder@${PROJECT_ID}.iam.gserviceaccount.com'