steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['pull']
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--build-arg'
    - 'USER_NAME=${USER}'
    - '--build-arg'
    - 'USER_UID=${_USER_UID}'
    - '--target'
    - 'production'
    - '-t'
    - $_IMAGE
    - '.'
  timeout: 300s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', $_IMAGE]
  timeout: 300s
images: [$_IMAGE]
options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _USER_UID: '1000'
  _LOCATION: 'us-west1'
  _REPOSITORY: 'yfin-mcp-server-images'
  _NAME: 'yfin'
  _VERSION: '1.0.0'
  _IMAGE: '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_NAME}:${_VERSION}'
serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/builder@${PROJECT_ID}.iam.gserviceaccount.com'